apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: cms
  labels:
    app: db
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port:
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: db-port
      targetPort:
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: db-port
      name: db-port
