apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: cms
  labels:
    app: db
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 5555
      targetPort: 5555
      name: db-port
