---
replicas: 1
minimumMasterNodes: 1
resources:
  requests:
    cpu: "100m"
    memory: "512M"
  limits:
    cpu: "1000m"
    memory: "512M"
volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "standard"
  resources:
    requests:
      storage: 100M
#antiAffinity: "soft"
#esJavaOpts: "-Xmx128m -Xms128m"
#protocol: http
clusterHealthCheckParams: "local=true"
