version: '3'

networks:
  wp:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    container_name: wordpress
    working_dir: /var/www/html/wordpress
    volume:
      - ./wordpress/:/var/www/html/wordpress/
    ports:
      - "80:80"
    environment:
      TZ: UTC+1
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    networks:
      - wp
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: mysql
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev-env
    networks:
      - wp
