resources:
  requests:
    cpu: "100m"
    memory: "512M"
  limits:
    cpu: "1000m"
    memory: "512M"
volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  storageClassName: "ebs-sc"
  resources:
    requests:
      storage: 5Gi
