resources:
  requests:
    cpu: "100m"
    memory: "512M"
  limits:
    cpu: "1000m"
    memory: "512M"
volumeClaimTemplate:
  accessModes: [""]
  storageClassName: ""
  resources:
    requests:
      storage:
